# Generated by Django 5.2.17 on 2026-10-09 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_main_piece', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ducky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ducky', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ducky', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('HISTORICAL', 'Pieza histórica'), ('COSMETIC', 'Cosmético'), ('ATTACK', 'Ataque'), ('DEFENSE', 'Defensa'), ('HINT', 'Pista')], max_length=16)),
                ('rarity', models.CharField(choices=[('COMMON', 'Común'), ('RARE', 'Raro'), ('EPIC', 'Épico'), ('LEGENDARY', 'Legendario')], default='COMMON', max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ducky_items/')),
                ('is_consumable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='duckies.equipmentslot')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EQUIP', 'Equipar'), ('UNEQUIP', 'Desequipar')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ducky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_history', to='duckies.ducky')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duckies.equipmentslot')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duckies.item')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('effect_code', models.CharField(choices=[('EXTRA_QUESTIONS', 'Preguntas extra'), ('TIME_ACCELERATION', 'Aceleración de tiempo'), ('SMOKE', 'Nube de humo'), ('SHIELD', 'Escudo'), ('EXTRA_TIME', 'Tiempo extra'), ('FIFTY_FIFTY', 'Eliminar respuestas'), ('EXTRA_HINT', 'Pista adicional')], max_length=30)),
                ('effect_value', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('effect_unit', models.CharField(blank=True, help_text='seconds, percent, questions, multiplier, etc.', max_length=24)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='duckies.item')),
            ],
            options={
                'ordering': ['item_id', 'level'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ducky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='duckies.ducky')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='duckies.item')),
                ('item_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='duckies.itemlevel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_key', models.CharField(max_length=255)),
                ('source_game', models.CharField(max_length=60)),
                ('session_id', models.CharField(max_length=100)),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ducky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_usages', to='duckies.ducky')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duckies.item')),
                ('item_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='duckies.itemlevel')),
            ],
        ),
        migrations.CreateModel(
            name='EquippedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped_at', models.DateTimeField(auto_now_add=True)),
                ('ducky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_items', to='duckies.ducky')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipped_items', to='duckies.equipmentslot')),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='duckies.inventoryitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ducky', 'slot'), name='duckies_unique_equipped_slot')],
            },
        ),
        migrations.CreateModel(
            name='EvolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.SlugField(max_length=60)),
                ('required_xp', models.PositiveBigIntegerField(default=0)),
                ('is_automatic', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolution_unlocks', to='duckies.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stage_code', 'item'), name='duckies_unique_stage_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='itemlevel',
            constraint=models.UniqueConstraint(fields=('item', 'level'), name='duckies_unique_item_level'),
        ),
        migrations.AddConstraint(
            model_name='itemlevel',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 3)), name='duckies_level_range'),
        ),
        migrations.AddConstraint(
            model_name='itemlevel',
            constraint=models.CheckConstraint(condition=models.Q(('effect_value__gte', 0)), name='duckies_effect_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_level__isnull', True)), fields=('ducky', 'item'), name='duckies_unique_base_inventory'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_level__isnull', False)), fields=('ducky', 'item_level'), name='duckies_unique_leveled_inventory'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='duckies_inventory_positive'),
        ),
        migrations.AddConstraint(
            model_name='itemusage',
            constraint=models.UniqueConstraint(fields=('ducky', 'operation_key'), name='duckies_unique_usage_key'),
        ),
        migrations.AddConstraint(
            model_name='itemusage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_used__gte', 1)), name='duckies_usage_positive'),
        ),
    ]
